services:
    Randock\DddPaginator\DataTransformer\DataTransformerInterface:
        class: Randock\DddPaginator\DataTransformer\DataTransformerInterface
    Randock\DddPaginator\DataTransformer\PaginatedDataTransformer:
        class: Randock\DddPaginator\DataTransformer\PaginatedDataTransformer
        arguments:
          - '@Randock\DddPaginator\DataTransformer\DataTransformerInterface'