services:
    Randock\DddPaginator\DataTransformer\PaginatedDataTransformer:
        class: Randock\DddPaginator\DataTransformer\PaginatedDataTransformer
        arguments:
          - '@Randock\DddPaginator\DataTransformer\DataTransformerInterface'